In [44]:
import numpy as np

In [54]:
def distance_corr(var_1, var_2, normedweight, power):
    
    xx = np.reshape(var_1, (-1, 1))
    print(xx)
    xx = np.tile(xx, (1, len(var_1)))
    print(xx)
#     xx = np.reshape(xx, (len(var_1), len(var_1)))
#     print(xx)
    yy = np.tile(var_1, (len(var_1), 1))
    #print(yy)
#     yy = np.reshape(yy, (len(var_1), len(var_1)))
#     print(yy)
    amat = abs(xx-yy)
    #print(amat)
    
    #print('var_2')
    xx = np.reshape(var_2, (-1, 1))
    #print(xx)
    xx = np.tile(xx, (1, len(var_2)))
    #print(xx)
#     xx = np.reshape(xx, (len(var_2),len(var_2)))
#     print(xx)
    yy = np.tile(var_2, (len(var_2), 1))
    #print(yy)
#     yy = np.reshape(yy, (len(var_2), len(var_2)))
#     print(yy)
    bmat = abs(xx-yy)
    #print(bmat)

    #print(amat)
    amatavg = np.mean(amat*normedweight, axis=1)
    #print(amatavg)
    amat1 = np.tile(amatavg, (len(var_1), 1))
    #print(amat1)
    #print(len(var_1))
#     amat1 = np.reshape(amat1, (len(var_1), len(var_1)))
#     print(amat1)
    amat2 = np.reshape(amatavg, (-1, 1))
    #print(amat2)
    amat2 = np.tile(amat2, (1, len(var_1)))
    #print(amat2)
#     amat2 = np.reshape(amat2, (len(var_1), len(var_1)))
#     print(amat2)
    amat3 = np.mean(amatavg*normedweight, axis=0)
    #print(amat3)
    Amat = amat - amat1 - amat2 + amat3
    
    #print(Amat)
    #print(amat)
    #print(amat1)
    #print(amat2)
    #print(amat3)
    #print(Amat)

    #print(len(yy))
    bmatavg = np.mean(bmat*normedweight, axis=1)
    #print(bmatavg)
    bmat1 = np.tile(bmatavg, (len(var_2), 1))
#     bmat1 = np.reshape(bmat1, (len(var_2), len(var_2)))
    bmat2 = np.reshape(bmatavg, (-1, 1))
    bmat2 = np.tile(bmat2, (1, len(var_2)))
#     bmat2 = np.reshape(bmat2, (len(var_2),len(var_2)))
    bmat3 = np.mean(bmatavg*normedweight, axis=0)
    Bmat = bmat - bmat1 - bmat2 + bmat3
    #print(Bmat)

    ABavg = np.mean(Amat*Bmat*normedweight, axis=1)
    AAavg = np.mean(Amat*Amat*normedweight, axis=1)
    BBavg = np.mean(Bmat*Bmat*normedweight, axis=1)
    #print(ABavg)
    #print(AAavg)
    #print(BBavg)

    if(power==1):
        dCorr=(np.mean(ABavg*normedweight))/np.sqrt((np.mean(AAavg*normedweight)*np.mean(BBavg*normedweight)))
    elif(power==2):
        dCorr=(np.mean(ABavg*normedweight))**2/(np.mean(AAavg*normedweight)*np.mean(BBavg*normedweight))
    else:
        dCorr=((np.mean(ABavg*normedweight))/np.sqrt((np.mean(AAavg*normedweight)*np.mean(BBavg*normedweight))))**power
    
    return dCorr

In [55]:
a = np.array([1, 2, 7, 4, 5])
b = np.array([1, 2, 1, 4, 4])
n = np.array([1, 1, 1, 1, 1])
p = 1

distance_corr(a, b, n, p)

[[1]
 [2]
 [7]
 [4]
 [5]]
[[1 1 1 1 1]
 [2 2 2 2 2]
 [7 7 7 7 7]
 [4 4 4 4 4]
 [5 5 5 5 5]]


0.366235125179238

In [4]:
a = np.array([[1, 2, 3, 4, 5], [1, 2, 9, 4, 4]])
b = np.array([[1, 2, 9, 4, 4], [1, 2, 3, 4, 5]])
n = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1 ,1]])
p = 1

#distance_corr(a, b, n, p)
distance_corr(a[0], b[0], n[0], p)

0.5816750507471109

In [10]:
# Olhar novamente o 'print(Amat)', apesar dos resultados serem os mesmos no "torch", 
#   a forma como eles são mostrado é diferente, estão elevados a alguma potência e possuem muitos zeros

# No 'np.mean', 'axis=0' é como se nada fosse definido, por isso nos 'if' ele não foi definido

In [48]:
a3 = np.array([7, 9])
b3 = np.array([3, 4])
n3 = np.array([1, 1])
p3 = 1

distance_corr(a3, b3, n3, p3)

1.0

In [47]:
Uniquesample = np.array([[7, 9], [6, 8], [0, 9]])
aux = np.array([[9, 8], [9, 8], [5, 9]])
n = np.array([[1, 1], [1, 1], [1, 1]])
p = 1
uspi = []

UN = 3
#UN = Uniquesample.shape
#print(UN)

#print(Uniquesample[0])
#print(aux[0])

#print(b.shape)
for i in range(UN):
    aux2 = np.power(distance_corr(Uniquesample[i], aux[i], n[i], p),2)
    uspi.append(aux2)
    
print(aux2)
print(uspi)

# aux2 = distance_corr(Uniquesample[0], aux[0], n[0], p)
# print(aux2)

    

1.0
[1.0, 1.0, 1.0]
