In [1]:
import numpy as np

In [78]:
def distance_corr(var_1, var_2, normedweight, power):
    
    print('var_1')
    xx = np.reshape(var_1, (-1, 1))
    print(xx)
    xx = np.tile(xx, (1, len(var_1)))
    print(xx)
#     xx = np.reshape(xx, (len(var_1), len(var_1)))
#     print(xx)
    yy = np.tile(var_1, (len(var_1), 1))
    print(yy)
#     yy = np.reshape(yy, (len(var_1), len(var_1)))
#     print(yy)
    amat = abs(xx-yy)
    print(amat)
    
    print('var_2')
    xx = np.reshape(var_2, (-1, 1))
    print(xx)
    xx = np.tile(xx, (1, len(var_2)))
    print(xx)
#     xx = np.reshape(xx, (len(var_2),len(var_2)))
#     print(xx)
    yy = np.tile(var_2, (len(var_2), 1))
    print(yy)
#     yy = np.reshape(yy, (len(var_2), len(var_2)))
#     print(yy)
    bmat = abs(xx-yy)
    print(bmat)

    print('Amat')
    amatavg = np.mean(amat*normedweight, axis=1)
    print(amatavg)
    amat1 = np.tile(amatavg, (len(var_1), 1))
    print(amat1)
#     amat1 = np.reshape(amat1, (len(var_1), len(var_1)))
#     print(amat1)
    amat2 = np.reshape(amatavg, (-1, 1))
    print(amat2)
    amat2 = np.tile(amat2, (1, len(var_1)))
    print(amat2)
#     amat2 = np.reshape(amat2, (len(var_1), len(var_1)))
#     print(amat2)
    amat3 = np.mean(amatavg*normedweight, axis=0)
    print(amat3)
    Amat = amat - amat1 - amat2 + amat3
    
    #print(Amat)
    #print(amat)
    #print(amat1)
    #print(amat2)
    #print(amat3)
    #print(Amat)

    print('Bmat')
    bmatavg = np.mean(bmat*normedweight, axis=1)
    print(bmatavg)
    bmat1 = np.tile(bmatavg, (len(var_2), 1))
#     bmat1 = np.reshape(bmat1, (len(var_2), len(var_2)))
    bmat2 = np.reshape(bmatavg, (-1, 1))
    print(bmat2)
    bmat2 = np.tile(bmat2, (1, len(var_2)))
    print(bmat2)
#     bmat2 = np.reshape(bmat2, (len(var_2),len(var_2)))
    bmat3 = np.mean(bmatavg*normedweight, axis=0)
    print(bmat3)
    Bmat = bmat - bmat1 - bmat2 + bmat3
    print(Bmat)

    ABavg = np.mean(Amat*Bmat*normedweight, axis=1)
    AAavg = np.mean(Amat*Amat*normedweight, axis=1)
    BBavg = np.mean(Bmat*Bmat*normedweight, axis=1)
    
    print('ABavg')
    print(ABavg)
    print('AAavg')
    print(AAavg)
    print('BBavg')
    print(BBavg)

    if(power==1):
        dCorr=(np.mean(ABavg*normedweight))/np.sqrt((np.mean(AAavg*normedweight)*np.mean(BBavg*normedweight)))
    elif(power==2):
        dCorr=(np.mean(ABavg*normedweight))**2/(np.mean(AAavg*normedweight)*np.mean(BBavg*normedweight))
    else:
        dCorr=((np.mean(ABavg*normedweight))/np.sqrt((np.mean(AAavg*normedweight)*np.mean(BBavg*normedweight))))**power
    
    return dCorr

In [79]:
a = np.array([-0.09006195,  1.490])
b = np.array([51.788092, 766878707])
n = np.array([1, 1])
p = 2

distance_corr(a, b, n, p)

var_1
[[-0.09006195]
 [ 1.49      ]]
[[-0.09006195 -0.09006195]
 [ 1.49        1.49      ]]
[[-0.09006195  1.49      ]
 [-0.09006195  1.49      ]]
[[0.         1.58006195]
 [1.58006195 0.        ]]
var_2
[[5.17880920e+01]
 [7.66878707e+08]]
[[5.17880920e+01 5.17880920e+01]
 [7.66878707e+08 7.66878707e+08]]
[[5.17880920e+01 7.66878707e+08]
 [5.17880920e+01 7.66878707e+08]]
[[0.00000000e+00 7.66878655e+08]
 [7.66878655e+08 0.00000000e+00]]
Amat
[0.79003097 0.79003097]
[[0.79003097 0.79003097]
 [0.79003097 0.79003097]]
[[0.79003097]
 [0.79003097]]
[[0.79003097 0.79003097]
 [0.79003097 0.79003097]]
0.790030975
Bmat
[3.83439328e+08 3.83439328e+08]
[[3.83439328e+08]
 [3.83439328e+08]]
[[3.83439328e+08 3.83439328e+08]
 [3.83439328e+08 3.83439328e+08]]
383439327.605954
[[-3.83439328e+08  3.83439328e+08]
 [ 3.83439328e+08 -3.83439328e+08]]
ABavg
[3.02928946e+08 3.02928946e+08]
AAavg
[0.62414894 0.62414894]
BBavg
[1.47025718e+17 1.47025718e+17]


0.9999999999999998

In [58]:
a = np.array([1, 2, 7, 4, 5])
b = np.array([1, 2, 1, 4, 4])
n = np.array([1, 1, 1, 1, 1])
p = 1

distance_corr(a, b, n, p)

0.366235125179238

In [4]:
a = np.array([[1, 2, 3, 4, 5], [1, 2, 9, 4, 4]])
b = np.array([[1, 2, 9, 4, 4], [1, 2, 3, 4, 5]])
n = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1 ,1]])
p = 1

#distance_corr(a, b, n, p)
distance_corr(a[0], b[0], n[0], p)

0.5816750507471109

In [10]:
# Olhar novamente o 'print(Amat)', apesar dos resultados serem os mesmos no "torch", 
#   a forma como eles são mostrado é diferente, estão elevados a alguma potência e possuem muitos zeros

# No 'np.mean', 'axis=0' é como se nada fosse definido, por isso nos 'if' ele não foi definido

In [48]:
a3 = np.array([7, 9])
b3 = np.array([3, 4])
n3 = np.array([1, 1])
p3 = 1

distance_corr(a3, b3, n3, p3)

1.0

In [47]:
Uniquesample = np.array([[7, 9], [6, 8], [0, 9]])
aux = np.array([[9, 8], [9, 8], [5, 9]])
n = np.array([[1, 1], [1, 1], [1, 1]])
p = 1
uspi = []

UN = 3
#UN = Uniquesample.shape
#print(UN)

#print(Uniquesample[0])
#print(aux[0])

#print(b.shape)
for i in range(UN):
    aux2 = np.power(distance_corr(Uniquesample[i], aux[i], n[i], p),2)
    uspi.append(aux2)
    
print(aux2)
print(uspi)

# aux2 = distance_corr(Uniquesample[0], aux[0], n[0], p)
# print(aux2)

    

1.0
[1.0, 1.0, 1.0]
