In [1]:
from scipy.spatial.distance import cdist, pdist, euclidean,pdist
import numpy as np

In [2]:
def alternativa_cdist(matrizA, matrizB):
    L1,_ = matrizA.shape
    L2,_ = matrizB.shape
    
    resultado = np.zeros((L1,L2))
    
    for i,a in enumerate(matrizA):
        for j,b in enumerate(matrizB):
            resultado[i,j] = euclidean(a,b)
            
    return resultado

In [3]:
def alternativa_pdist(matrixA):
    L, W = matrixA.shape
    resultado = np.zeros((L**2+L-(L**2+3*L+2)//2)+1)
    for i in range(L):
        for j in range(i,L):
            if i != j:
                resultado[L * i + j - ((i + 2) * (i + 1)) // 2] = euclidean(matrixA[i], matrixA[j])
    return resultado

In [4]:
matrizA = np.array([[1,1],
                [2,2],
                [3,3],
                [4,4],
                [5,5]])

matrizB = np.array([[1,1],
                [3,3],
               [5,5]])

In [5]:
resultado_cdist = cdist(matrizA, matrizB)

resultado_cdist2 = alternativa_cdist(matrizA,matrizB)

print('------------------------ CDIST ----------------------- ')
print("Resultado CDIST")
print(resultado_cdist)

print("\nResultado Atlernativa CDIST")
print(resultado_cdist2)

print("\nComparacao")
print(resultado_cdist-resultado_cdist2)
print(sum(sum(resultado_cdist-resultado_cdist2)))

------------------------ CDIST ----------------------- 
Resultado CDIST
[[0.         2.82842712 5.65685425]
 [1.41421356 1.41421356 4.24264069]
 [2.82842712 0.         2.82842712]
 [4.24264069 1.41421356 1.41421356]
 [5.65685425 2.82842712 0.        ]]

Resultado Atlernativa CDIST
[[0.         2.82842712 5.65685425]
 [1.41421356 1.41421356 4.24264069]
 [2.82842712 0.         2.82842712]
 [4.24264069 1.41421356 1.41421356]
 [5.65685425 2.82842712 0.        ]]

Comparacao
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
0.0


In [6]:
resultado_pdist = pdist(matrizA)

resultado_pdist2 = alternativa_pdist(matrizA)

print('\n\n\n------------------------ PDIST ----------------------- ')
print("Resultado PDIST")
print(resultado_pdist)

print("\nResultado Atlernativa PDIST")
print(resultado_pdist2)


print("\nComparacao")
print(resultado_pdist-resultado_pdist2)
print(sum(resultado_pdist-resultado_pdist2))




------------------------ PDIST ----------------------- 
Resultado PDIST
[1.41421356 2.82842712 4.24264069 5.65685425 1.41421356 2.82842712
 4.24264069 1.41421356 2.82842712 1.41421356]

Resultado Atlernativa PDIST
[1.41421356 2.82842712 4.24264069 5.65685425 1.41421356 2.82842712
 4.24264069 1.41421356 2.82842712 1.41421356]

Comparacao
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0
