In [5]:
from scipy.spatial.distance import cdist, euclidean,pdist
import numpy as np

In [6]:
def funcao(matrizA, matrizB):
    L1,_ = matrizA.shape
    L2,_ = matrizB.shape
    
    resultado = np.zeros((L1,L2))
    
    for i,a in enumerate(matrizA):
        for j,b in enumerate(matrizB):
            resultado[i,j] = euclidean(a,b)
            
    return resultado

In [7]:
matrizA = np.array([[1,1],
                [2,2]])

matrizB = np.array([[1,1],
                [3,3],
               [5,5]])

In [8]:
resultado_cdist = cdist(matrizA, matrizB)

resultado_funcao = funcao(matrizA,matrizB)

In [9]:
print("Resultado CDIST")
print(resultado_cdist)

print("Resultado Funcao")
print(resultado_funcao)

Resultado CDIST
[[0.         2.82842712 5.65685425]
 [1.41421356 1.41421356 4.24264069]]
Resultado Funcao
[[0.         2.82842712 5.65685425]
 [1.41421356 1.41421356 4.24264069]]
