In [1]:
import numpy as np

In [20]:
def distance_corr(var_1, var_2, normedweight, power):
    
    xx = np.reshape(var_1, (-1, 1))
    #print(xx)
    #print(len(var_1))
    #print(len(xx))
    xx = np.tile(xx, (1, len(xx))) #Mudança
    #print(xx)
    #print(len(xx))
    xx = np.reshape(xx, (len(xx), len(xx))) #Mudança
    #print(xx)
    yy = np.reshape(var_1, (1, -1)) #Adicionado
    #print(yy.shape)
    #print(yy)
    #print(len(yy))
    yy = np.tile(yy, (len(xx), 1)) #Mudança
    #print(yy)
    #print(len(var_1))
    #print(len(xx))
    #print(len(yy))
    yy = np.reshape(yy, (len(yy), len(yy))) #Mudança
    #print(yy)
    amat = abs(xx-yy)
    #print(amat)
    
    xx = np.reshape(var_2, (-1, 1))
    #print(xx)
    xx = np.tile(xx, (1, len(xx))) #Mudança
    #print(xx)
    xx = np.reshape(xx, (len(xx),len(xx))) #Mudança
    #print(xx)
    yy = np.reshape(var_2, (1, -1)) #Adicionado
    yy = np.tile(yy, (len(xx), 1)) #Mudança
    #print(yy)
    yy = np.reshape(yy, (len(yy), len(yy))) #Mudança
    #print(yy)
    bmat = abs(xx-yy)
    #print(bmat)

    normedweight = np.reshape(normedweight, (1, -1)) #Adicionado
    normedweight = np.tile(normedweight, (len(xx), 1)) #Adicionado
    print(normedweight)
    
    #print(amat)
    amatavg = np.mean(amat*normedweight, axis=1)
    #print(amatavg)
    amat1 = np.tile(amatavg, (len(xx), 1)) #Mudança
    #print(amat1)
    #print(len(var_1))
    amat1 = np.reshape(amat1, (len(xx), len(xx))) #Mudança
    #print(amat1)
    amat2 = np.reshape(amatavg, (-1, 1))
    #print(amat2)
    amat2 = np.tile(amat2, (1, len(xx))) #Mudança
    #print(amat2)
    amat2 = np.reshape(amat2, (len(xx), len(xx))) #Mudança
    #print(amat2)
    amat3 = np.mean(amatavg*normedweight, axis=0)
    amat3 = np.mean(amat3, axis=0) #Adicionado
    #print(amat3)
    Amat = amat - amat1 - amat2 + amat3
    #print(Amat)
    #print(amat)
    #print(amat1)
    #print(amat2)
    #print(amat3)
    #print(Amat)

    #print(len(yy))
    bmatavg = np.mean(bmat*normedweight, axis=1)
    #print(bmatavg)
    bmat1 = np.tile(bmatavg, (len(yy), 1)) #Mudança
    bmat1 = np.reshape(bmat1, (len(yy), len(yy))) #Mudança
    bmat2 = np.reshape(bmatavg, (-1, 1))
    bmat2 = np.tile(bmat2, (1, len(yy))) #Mudança
    bmat2 = np.reshape(bmat2, (len(yy),len(yy))) #Mudança
    bmat3 = np.mean(bmatavg*normedweight, axis=0)
    bmat3 = np.mean(bmat3, axis=0) #Adicionado
    Bmat = bmat - bmat1 - bmat2 + bmat3
    #print(Bmat)

    ABavg = np.mean(Amat*Bmat*normedweight, axis=1)
    AAavg = np.mean(Amat*Amat*normedweight, axis=1)
    BBavg = np.mean(Bmat*Bmat*normedweight, axis=1)
    #print(ABavg)
    #print(AAavg)
    #print(BBavg)

    if(power==1):
        dCorr=(np.mean(ABavg*normedweight))/np.sqrt((np.mean(AAavg*normedweight)*np.mean(BBavg*normedweight)))
    elif(power==2):
        dCorr=(np.mean(ABavg*normedweight))**2/(np.mean(AAavg*normedweight)*np.mean(BBavg*normedweight))
    else:
        dCorr=((np.mean(ABavg*normedweight))/np.sqrt((np.mean(AAavg*normedweight)*np.mean(BBavg*normedweight))))**power
    
    return dCorr

In [21]:
a = np.array([[1, 2, 3, 4, 5], [1, 2, 9, 4, 4]])
b = np.array([[1, 2, 9, 4, 4], [1, 2, 3, 4, 5]])
n = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1 ,1]])
p = 1

distance_corr(a, b, n, p)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


0.5297522155905229

In [18]:
a = np.array([1, 2, 7, 4, 5])
b = np.array([1, 2, 1, 4, 4])
n = np.array([1, 1, 1, 1, 1])
p = 1

distance_corr(a, b, n, p)

[[0 1 6 3 4]
 [1 0 5 2 3]
 [6 5 0 3 2]
 [3 2 3 0 1]
 [4 3 2 1 0]]
[[0 1 0 3 3]
 [1 0 1 2 2]
 [0 1 0 3 3]
 [3 2 3 0 0]
 [3 2 3 0 0]]
5
[1.4 1.2 1.4 1.6 1.6]
[0.96  0.576 0.256 0.96  1.088]
[4.352 2.432 5.312 0.512 1.472]
[1.5744 0.3584 1.5744 2.1504 2.1504]


0.366235125179238

In [12]:
# Olhar novamente o 'print(Amat)', apesar dos resultados serem os mesmos no "torch", 
#   a forma como eles são mostrado é diferente, estão elevados a alguma potência e possuem muitos zeros

# No 'np.mean', 'axis=0' é como se nada fosse definido, por isso nos 'if' ele não foi definido