In [1]:
import numpy as np

In [2]:
import torch

In [3]:
# Repeat e tile

In [4]:
x = torch.tensor([1, 2, 3])
x.repeat(4, 2)

tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])

In [5]:
x1 = np.array([1, 2, 3])
np.tile(x1,(4,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [6]:
# View e reshape

In [7]:
y = torch.tensor([1, 2, 3])
y.view(-1, 1)

tensor([[1],
        [2],
        [3]])

In [8]:
y1 = np.array([1, 2, 3])
np.reshape(y1, (-1,1))

array([[1],
       [2],
       [3]])

In [9]:
# União torch

xx = x.view(-1, 1).repeat(1, len(x)).view(len(x),len(x))

In [10]:
# União numpy

xx = x1.reshape(-1, 1).tile(len(var_1), 1).reshape(len(var_1),len(var_1))
yy = var_1.tile(len(var_1), 1).reshape(len(var_1), len(var_1))
amat = abs(xx-yy)

AttributeError: 'numpy.ndarray' object has no attribute 'tile'

In [ ]:
xx = np.reshape(x1, (-1, 1))
xx = np.tile(xx, (len(x1), 1))
xx = np.reshape(xx, (len(x1),len(x1)))

yy = np.tile(x1, (len(x1), 1))
yy = np.reshape(yy, (len(x1), len(x1)))
amat = abs(xx-yy)

In [ ]:
uu = torch.tensor([1, 2, 3])

uu = uu.repeat(4 , 1)

print(uu)

In [11]:
y2 = np.array([1, 2, 3])
x2 = len(y2)
print(x2)

3
